Gibbs Sampling From Simulated Data

In [1]:
import numpy as np

In [19]:
# Generate a random copy number vector with uniform distribution over support.
n_targets = 78
cnv_support = [1, 2, 3]
copy_numbers = np.random.choice(cnv_support, n_targets)
copy_numbers

array([2, 3, 3, 1, 1, 2, 3, 1, 3, 3, 2, 3, 1, 1, 1, 3, 2, 2, 2, 1, 2, 2, 2,
       1, 2, 1, 3, 2, 2, 1, 3, 2, 2, 1, 2, 1, 3, 1, 3, 3, 3, 1, 3, 2, 3, 3,
       1, 1, 2, 1, 3, 2, 1, 2, 1, 1, 3, 1, 1, 3, 1, 3, 1, 1, 1, 3, 3, 3, 2,
       2, 2, 1, 2, 2, 1, 1, 1, 1])

In [21]:
# Compute a fixed intensity vector which is uniform.
intensity = np.ones(len(copy_numbers))/len(copy_numbers)
intensity

array([ 0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01282051,
        0.01282051,  0.01282051,  0.01282051,  0.01282051,  0.01

In [22]:
# Draw samples that reflect this distribution.
p_vector = copy_numbers * intensity
p_vector /= float(np.sum(p_vector))
samples = np.random.multinomial(20000, p_vector)
samples

array([297, 405, 381, 145, 133, 255, 445, 136, 370, 392, 260, 419, 132,
       147, 132, 380, 261, 289, 270, 143, 307, 263, 243, 148, 236, 143,
       414, 304, 265, 135, 380, 235, 272, 130, 264, 104, 395, 138, 388,
       391, 382, 154, 407, 266, 442, 410, 150, 111, 276, 134, 366, 267,
       129, 278, 146, 150, 432, 136, 133, 396, 132, 429, 146, 126, 137,
       427, 405, 432, 284, 286, 260, 130, 269, 311, 125, 140, 137, 112])

In [ ]:
# Use Gibbs' method to sample the posterior of the prior + data generated from the prior.
